// <auto-generated />
using System;
using Bot.Core.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bot.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bot.Core.Model.Estudante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Autenticado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("autenticado");

                    b.Property<string>("Ciclo")
                        .HasColumnType("longtext")
                        .HasColumnName("ciclo");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmailInstitucional")
                        .HasColumnType("longtext")
                        .HasColumnName("email_institucional");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("PP")
                        .HasColumnType("longtext")
                        .HasColumnName("pp");

                    b.Property<string>("PR")
                        .HasColumnType("longtext")
                        .HasColumnName("pr");

                    b.Property<int?>("PreferenciaId")
                        .HasColumnType("int")
                        .HasColumnName("preferencia_id");

                    b.Property<string>("Ra")
                        .HasColumnType("longtext")
                        .HasColumnName("ra");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PreferenciaId");

                    b.ToTable("estudante");
                });

            modelBuilder.Entity("Bot.Core.Model.Faltas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Ausencias")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("MaximoAusencia")
                        .HasColumnType("int")
                        .HasColumnName("maximo_ausencias");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes");

                    b.Property<int?>("Presencas")
                        .HasColumnType("int")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("faltas");
                });

            modelBuilder.Entity("Bot.Core.Model.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("EstudanteId")
                        .HasColumnType("int")
                        .HasColumnName("estudante_id");

                    b.Property<int?>("FaltasId")
                        .HasColumnType("int")
                        .HasColumnName("faltas_id");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int?>("NotasId")
                        .HasColumnType("int")
                        .HasColumnName("notas_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes");

                    b.Property<string>("Professor")
                        .HasColumnType("longtext")
                        .HasColumnName("professor");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EstudanteId");

                    b.HasIndex("FaltasId");

                    b.HasIndex("NotasId");

                    b.ToTable("materia");
                });

            modelBuilder.Entity("Bot.Core.Model.Notas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<float?>("MediaFinal")
                        .HasColumnType("float")
                        .HasColumnName("media_final");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes");

                    b.Property<float?>("P1")
                        .HasColumnType("float")
                        .HasColumnName("p1");

                    b.Property<float?>("P2")
                        .HasColumnType("float")
                        .HasColumnName("p2");

                    b.Property<float?>("P3")
                        .HasColumnType("float")
                        .HasColumnName("p3");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("Bot.Core.src.Model.Preferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AtualizarPorEmail")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_atualizar_por_email");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("longtext")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.ToTable("preferencia");
                });

            modelBuilder.Entity("Bot.Core.Model.Estudante", b =>
                {
                    b.HasOne("Bot.Core.src.Model.Preferencia", "Preferencia")
                        .WithMany()
                        .HasForeignKey("PreferenciaId");

                    b.Navigation("Preferencia");
                });

            modelBuilder.Entity("Bot.Core.Model.Materia", b =>
                {
                    b.HasOne("Bot.Core.Model.Estudante", null)
                        .WithMany("Materias")
                        .HasForeignKey("EstudanteId");

                    b.HasOne("Bot.Core.Model.Faltas", "Faltas")
                        .WithMany()
                        .HasForeignKey("FaltasId");

                    b.HasOne("Bot.Core.Model.Notas", "Notas")
                        .WithMany()
                        .HasForeignKey("NotasId");

                    b.Navigation("Faltas");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Bot.Core.Model.Estudante", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
